language: php
php:
- 5.5
env:
  global:
  - PUUID='b19020fa-e69f-4555-8e04-a711bd343414'
  - PNAME='Tickets'
  - PEMAIL='timani@getpantheon.com'
before_install:
install:
- bash scripts/install.sh
before_script: 
script:
- bash scripts/run_tests.sh
after_script: 
after_success: 
after_failure: 
notifications:
  email:
    recipients: 
    on_success: always
    on_failure: always
