language: php
php:
- 5.5
env:
  global:
  - PUUID='f86d7c5d-db0a-45f4-8a8a-dc0c37964bc1'
  - PNAME='Tickets'
  - PEMAIL='timani@getpantheon.com'
before_install:
- openssl aes-256-cbc -K $encrypted_993c032d5299_key -iv $encrypted_993c032d5299_iv
  -in travis-ci-key.pub.enc -out travis-ci-key.pub -d
install:
- bash scripts/install.sh
before_script: 
script:
- bash scripts/run_tests.sh
after_script: 
after_success: 
after_failure: 
notifications:
  email:
    recipients: 
    on_success: always
    on_failure: always
