language: php
php:
  - 5.5
env:
  global:
    # Your Pantheon site's UUID (e.g. from your dashboard URL)
    - PUUID='f86d7c5d-db0a-45f4-8a8a-dc0c37964bc1'
    # Your Pantheon site's name.
    - PNAME='Tickets'
    # The user you interact with Pantheon as
    - PEMAIL='timani@getpantheon.com'
before_install:
    # Place a passphrase-free ssh key so that you can clone and push to your
    # Pantheon git repository.
    #
    # Use the travis encrypt-file command to generate your own.
    #
    # See: http://docs.travis-ci.com/user/encrypting-files/
    #
    - openssl aes-256-cbc -K $encrypted_993c032d5299_key -iv $encrypted_993c032d5299_iv -in travis-ci-key.pub.enc -out travis-ci-key.pub -d
    - chmod 0600 ~/.ssh/id_rsa

install:
    - bash scripts/install.sh

before_script:
  # Could add more things to prep for the test run here.

script:
    # - bash scripts/run_tests.sh
after_script:
  # General-purpose clean-up could go here.
after_success:
  # Maybe promote to test here?
after_failure:
  # Maybe roll back? 
notifications:
  email:
    recipients:
      # - panopoly-ci@googlegroups.com
    on_success: always
    on_failure: always
